  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: read-pods
    namespace: dev

  subjects:
  - kind: ServiceAccount
    name: build-root
    namespace: dev
  roleRef:
    kind: Role
    name: devRole
    apiGroup: rbac.authorization.k8s.io