apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  selector:
    matchLabels:
      app: frontend-deploy
  template:
    metadata:
      labels:
        app: frontend-deploy
    spec:
      containers:
        - name: frontend-deploy
          image: public.ecr.aws/n1z3k8d0/micro-app-fe
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: micro-config-map
            - secretRef:
                name: micro-secret
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000

--- 

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend-deploy
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
  type: NodePort

