apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
spec:
  selector:
    matchLabels:
      app: customer-deploy
  template:
    metadata:
      labels:
        app: customer-deploy
    spec:
      containers:
        - name: customer-deploy
          image: public.ecr.aws/n1z3k8d0/micro-app-customer
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: micro-config-map
            - secretRef:
                name: micro-secret
          resources:
            limits:
              memory: "250Mi"
              cpu: "100m"
          ports:
            - containerPort: 8003

--- 

apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector:
    app: customer-deploy
  ports:
  - port: 8003
    targetPort: 8003
    nodePort: 30003
  type: NodePort

